### DISCUSSION TITLE
请问侧边栏挂件的逻辑是什么

### DISCUSSION THREAD

**Discussion by glimmeringlight** [xaoxuu/hexo-theme-stellar#129] [Q&A] [answered]
在`_config.stellar.yaml`如下配置后，
```yaml
sidebar:
    widget_layout:
        index: [welcome] # for home/wiki/categories/tags/archives/404 pages
        page: [] # for pages using 'layout:page'
        post: [toc] # for pages using 'layout:post'
        wiki: [] # for pages using 'layout:wiki'
```
主页侧边栏是不是只应该出现`welcome`这个挂件，但实际上还有`recent`和`ghuser`。
![image](https://user-images.githubusercontent.com/99467198/196018596-5a7ad478-086c-4dda-b439-8075d26628c3.png)
