### DISCUSSION TITLE
1.14.0

### DISCUSSION THREAD

**Discussion by xaoxuu** [xaoxuu/hexo-theme-stellar#162] [Announcements]
- `A` 时间线标签支持隐藏 `user`
- `A` 侧边栏时间线组件支持显示朋友圈数据
- `F` 修复时间线在 Windows 系统部分浏览器显示滚动条的BUG
- `M` 优化 `link` 标签数据填充逻辑，已有数据不再覆盖。
- `M` 优化部分默认样式，例如封面、时间线
- `M` 为避免歧义，文章封面全图卡片字段调整：
```yaml
poster: # 海报（可选，全图封面卡片，需搭配 cover 使用）
  topic: 标题上方的小字 # 可选
  headline: 大标题 # 必选，否则不生效
  caption: 标题下方的小字 # 可选
  color: 标题颜色 # white, red...，默认为跟随主题的动态颜色 
```

<hr /><em>This discussion was created from the release <a href='https://github.com/xaoxuu/hexo-theme-stellar/releases/tag/1.14.0'>1.14.0</a>.</em>
