### ISSUE TITLE
页面滚动时底部不能加载出来

### ISSUE THREAD

**Issue by i-abc** [xaoxuu/hexo-theme-stellar#130]
如图所示：

![image](https://user-images.githubusercontent.com/104631897/196031462-66e0d870-cc65-4e14-b442-01ff08959a0e.png)

正常情况：

![image](https://user-images.githubusercontent.com/104631897/196031665-0e11fbd2-91c7-4ece-94c4-9e373564c18f.png)

我`lazyload`、`scrollreveal`均开启了的：
```yaml
  # image lazyload
  # https://www.npmjs.com/package/vanilla-lazyload
  lazyload:
    enable: true # [hexo clean && hexo s] is required after changing this value.
    js: https://other.shifeiti.com/blog/theme/_config/lazyload.min.js # https://fastly.jsdelivr.net/npm/vanilla-lazyload@17.3.1/dist/lazyload.min.js
    transition: blur # blur, fade

  # https://scrollrevealjs.org/api/reveal.html
  scrollreveal:
    enable: true
    js: https://other.shifeiti.com/blog/theme/_config/scrollreveal.min.js # https://fastly.jsdelivr.net/npm/scrollreveal@4.0.9/dist/scrollreveal.min.js
    distance: 8px
    duration: 500 # ms
    interval: 100 # ms
    scale: 1 # 0.1~1
```

在关闭`lazyload`、`scrollreveal`其中的一个后则可以正常加载了，但加载过程没那么美观了，请问这能解决吗？

复现链接：[https://www.shifeiti.com](https://www.shifeiti.com)
