### ISSUE TITLE
项目页面的「返回所有项目」错误

### ISSUE THREAD

**Issue by deskside** [xaoxuu/hexo-theme-stellar#167]
<img width="729" alt="image" src="https://user-images.githubusercontent.com/68626438/200178482-193550e7-2837-4fdd-a624-680cc0339477.png">

点击图中按钮后，返回的是「文章」（即博客主页面）菜单，而不是「项目」所在的分菜单。

<img width="429" alt="image" src="https://user-images.githubusercontent.com/68626438/200178578-d9c0c802-2501-41d8-bfb0-880d0def5ef6.png">

**Comment by xaoxuu** [comment]
你看看我的是对的吗

**Comment by deskside** [comment]
@xaoxuu 您的是对的！我不知道是我配置有错误还是怎么回事hhh🙇‍♂️

**Comment by xaoxuu** [comment]
你发一下根目录的配置文件看看

**Comment by deskside** [comment]
久等了，麻烦您 @xaoxuu  了！

## config.stellar.yml

```

article:
  # 如果没有指定封面，是否根据 tags 作为关键词搜索封面图片？
  auto_cover: false # search from https://source.unsplash.com/
  # 如果没有指定横幅，是否根据 tags 作为关键词搜索横幅图片？
  auto_banner: false # search from https://source.unsplash.com/
  # 如果没有指定 excerpt 和 description，将自动取多长的内容作为文章摘要？
  auto_excerpt: 100
  # 分类颜色
  category_color:
    '我的人生哲学': '#DA0F47'
  # 文章许可协议
  license: '本文采用[署名-非商业性使用-相同方式共享 4.0 国际](https://creativecommons.org/licenses/by-nc-sa/4.0/)许可协议，转载请注明出处。'
  # 分享
  share:  [wechat, weibo, email, link]
  # 相关文章，需要安装插件 (for layout: post)
  # npm i hexo-related-popular-posts
  related_posts:
    enable: false
    max_count: 5

style:
  darkmode: auto # auto / always / false
  smooth_scroll: true # true / false
  font-size: 16px
  font-family:
    logo: 'system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    body: 'system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    code: 'Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif'
  color:
    common:
      theme: '#1BCDFC' # 主题色
      accent: '#ff5722' # 强调色
      link: '#ff5722' # 超链接颜色
      button: '#1BCDFC' # 按钮颜色
      hover: '#ff5722' # 按钮高亮颜色
    light:
      background: '#f8f8f8' # 浅色背景颜色
      block: '#f2f2f2' # 块背景颜色
      card: white # 卡片背景颜色
      title: '#000' # 标题文本颜色
      text: '#333' # 正文文本颜色
      code: '#111' # 行内代码颜色
    dark:
      background: '#313438' # 深色背景颜色
      background-mobile: black # 移动端深色背景（OLED调成纯黑可以省电）
      block: '#2B2F33' # 块背景颜色
      card: '#464D57' # 卡片背景颜色
      title: '#fff' # 标题文本颜色
      text: '#eee' # 正文文本颜色
      code: '#ff7043' # 行内代码颜色
   
open_graph:
  enable: true
  twitter_id: # for open_graph meta
  
sidebar:
  logo:
    avatar: '[config.avatar](/about/)' # you can set avatar link in _config.yml or '[https://xxx.png](/about/)'
    title: '[config.title](/)' # you can set html tag like: '[<img no-lazy height="32px" src="xxx"/>](/)'
  widgets:
    index: [welcome, recent, timeline] # for home/wiki/categories/tags/archives/404 pages
    page: [welcome, toc] # for pages using 'layout:page'
    post: [toc, ghrepo, ghissues] # for pages using 'layout:post'
    wiki: [toc, ghrepo, ghissues, related] # for pages using 'layout:wiki'
  menu:
    post: '[btn.blog](/)'
    wiki: '[btn.wiki](/wiki/)'
    more: '[关于](/about/)'
    
  
# 默认打开
loading:
  loading: 正在加载
  error: 加载失败，请稍后重试。
  
# 默认打开
lazyload:
  enable: true # [hexo clean && hexo s] is required after changing this value.
  js: https://fastly.jsdelivr.net/npm/vanilla-lazyload@17.3.1/dist/lazyload.min.js
  transition: blur # blur, fade
  
# 评论
comments:
  service: giscus
  # giscus
  # https://giscus.app/zh-CN
  giscus:
    data-repo: "deskside/deskside.github.io" # [在此输入仓库]
    data-repo-id: "R_kgDOHlARng" # [在此输入仓库 ID]
    data-category: "Announcements" # [在此输入分类名]
    data-category-id: "DIC_kwDOHlARns4CSYZO"
    data-mapping: pathname
    data-strict: 0
    data-reactions-enabled: 1
    data-emit-metadata: 0
    data-input-position: top # top, bottom
    data-theme: preferred_color_scheme
    data-lang: zh-CN
    data-loading: lazy
    crossorigin: anonymous



footer:
  social:
    github: 
      icon: '<img src="https://fastly.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/08a41b181ce68.svg"/>'
      url: https://github.com/deskside
    # music:
    #   icon: '<img src="https://fastly.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/3845874.svg"/>'
    #   url: /
    # unsplash:
    #   icon: '<img src="https://fastly.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/3616429.svg"/>'
    #   url: /
    # comments:
    #   icon: '<img src="https://fastly.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/942ebbf1a4b91.svg"/>'
    #   url: /about/#comments
  sitemap:
    #'博客':
    #  - '[近期](/)'
    #  - '[分类](/)'
    #  - '[标签](/)'
    #  - '[归档](/)'
    # '项目':
    #  - '[开源库](/)'
    #'社交':
    #  - '[友链](/)'
    #  - '[留言板](/)'
    #'更多':
    #  - '[关于本站](/)'
    #  - '[GitHub](/)'
  content: | # 支持 Markdown 格式
    本站由 [@deskside](/) 使用 [Stellar](https://github.com/xaoxuu/hexo-theme-stellar) 主题创建。
    本博客所有文章除特别声明外，均采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。
  # 主题用户越多，开发者维护和更新的积极性就越高，如果您喜欢本主题，请在适当的位置显示主题信息和仓库链接以表支持。

```

## config.stellar.yml

```

# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Deskside
subtitle: 桌沿是我 | 我是桌沿
description: ''
keywords:
author: John Doe
language:
  - zh-CN
  - en
timezone: ''
avatar: /img/me.png
favicon: /img/me.png

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://example.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: stellar

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:deskside/deskside.github.io.git
  branch: master

```
