### ISSUE TITLE
我得评论插件遇到问题了，如图，大佬帮看下

### ISSUE THREAD

**Issue by czsmall** [xaoxuu/hexo-theme-stellar#171]

**Comment by czsmall** [comment]
![image](https://user-images.githubusercontent.com/110958481/200737260-9f8388bd-41a0-45e4-8fd0-e8fc5f74c128.png)

**Comment by weekdaycare** [comment]
你的`https://`呢？

**Comment by czsmall** [comment]
加于不加报同样得错

**Comment by weekdaycare** [comment]
缩进问题……你改动过了，你对照stellar官方文档看看吧。service和waline是同一列的

**Comment by xaoxuu** [comment]
好像文档上也是缩进有问题😅

**Comment by czsmall** [comment]
![image](https://user-images.githubusercontent.com/110958481/200741808-cfc26cd0-8047-4689-b4c0-1c7d6743792a.png)

**Comment by czsmall** [comment]
> 好像文档上也是缩进有问题😅

检查过了，同一列

**Comment by czsmall** [comment]
是不是要放到最下面

**Comment by weekdaycare** [comment]
```yml
comments:
  service: waline # beaudar, utterances, valine, twikoo, waline
  waline:
    js: 
    css: 
    # Waline server address url, you should set this to your own link
    serverURL: https://
```
文档也有问题，你这样写
