### ISSUE TITLE
请问页脚的社交链接仅支持3个吗？我设置了4个但是第四个一直无法显示出来

### ISSUE THREAD

**Issue by deskside** [xaoxuu/hexo-theme-stellar#172]
![image](https://user-images.githubusercontent.com/68626438/200785631-f5b0af17-2e3b-43a4-9bfb-51649e339bbd.png)

```
footer:
  social:
    github: 
      icon: '<img src="https://s2.loli.net/2022/11/08/BxmHlK6oeFp1sa5.png"/>'
      url: https://github.com/deskside
    jike:
      icon: '<img src="https://s2.loli.net/2022/11/08/Mq483RifVtl7dzI.png"/>'
      url: https://web.okjike.com/u/8a6595bb-1f2d-4b0e-a2a6-43a205f4d1a9
    youtube:
      icon: '<img src="https://s2.loli.net/2022/11/08/wylM6ImdsDzqY4Z.png"/>'
      url: https://www.youtube.com/channel/UCDHwHAiT-jJ4AACLHir70Fg
    redbook:
      icons: '<img src="https://s2.loli.net/2022/11/08/lXdaYRPLmjgVvEb.png"/>'
      url: https://www.xiaohongshu.com/user/profile/59f333324eacab131181dc7a?xhsshare=CopyLink&appuid=59f333324eacab131181dc7a&apptime=1667917567
```
