### ISSUE TITLE
现在的 wiki 能直接引用博客中的文章吗？

### ISSUE THREAD

**Issue by oec2003** [xaoxuu/hexo-theme-stellar#173]
例如：

1、我在学习 go 语言编程，写了一系列的博客文章，中间又穿插写了些别的；

2、我想对 go 语言学习笔记创建一个 wiki ，文章想用之前博客中的文章，组织成 wiki 的形式。

不知道现在能支持吗？

谢谢！

**Comment by weekdaycare** [comment]
试试
```
---
# wiki/index.md
layout: wiki
wiki: go
title: GO语言
order: 1
---
```

```
# project.yml
go:
  name: Go语言
  title: Go语言
  subtitle: 
  description: 
  index: true # 不在wiki列表中索引这个项目
  tags: 
  sections:
    '1': [0, 99]
    '2': [100, 199]
    '3': [200, 299]
```
