### ISSUE TITLE
默认的导航栏和侧边栏无法关闭

### ISSUE THREAD

**Issue by hermitlsr** [xaoxuu/hexo-theme-stellar#19]
## 版本
通过git安装的1.4.0版

## bug
默认的welcome组件无法关闭，在默认页`home/wiki/categories/tags/archives`，即使更改组件名为 `notice` 并设置 ：`default_layout: [notice, recent]` welcome 内容仍然存在，且不会出现notice内容。但在 about页更换标签名是有效的。

查看过历史issue看到这个问题被修复过，但不知道为什么这个新版本还是有问题

## 详情截图
![image](https://user-images.githubusercontent.com/84276102/127171415-5a7ec2c9-8a0c-42f4-9bb6-392c455ba0d0.png)
![](https://bu.dusays.com/2021/07/27/5678bf5321367.png)

## 配置
```yml
  widgets:
    # default layout in home/wiki/categories/tags/archives pages
    default_layout: [notice, recent]
    # Recent update
    recent:
      layout: recent
      rss: # /atom.xml # npm i hexo-generator-feed
      limit: 5 # Count of posts
    # TOC (valid only in layout:post/wiki)
    toc:
      layout: toc
      list_number: false
      min_depth: 2
      max_depth: 5
      fallback: recent # Use a backup widget when toc does not exist.
    # welcome
    notice:
      layout: markdown
      title: 欢迎
      content:
        - '欢迎光临小站'
```

**Comment by xaoxuu** [comment]
默认的 `welcome` 只在配置文件里有一份，如果你改掉了还能看到，请检查：
1. 是否执行了 `hexo clean` 后重新 `hexo s`
2. 是否自己多复制了一份到数据文件里

**Comment by hermitlsr** [comment]
> 默认的 `welcome` 只在配置文件里有一份，如果你改掉了还能看到，请检查：
> 
> 1. 是否执行了 `hexo clean` 后重新 `hexo s`
> 2. 是否自己多复制了一份到数据文件里

我仔细检查了一下:

1.  我的命令是 `hexo c && hexo g && hexo s`，并且尝试过删除 `public` 文件夹，以及删除浏览器缓存。
 
2.  我的`_data` 文件中仅有 `friend.yml`  、`project.yml` 以及 `sites.yml` 并无 `widgers.yml` .

3. 另外我今天测试发现，更改名称后的notice是出现了的，只不过出现在最下方，详情如图：
![](https://bu.dusays.com/2021/07/28/7f7622a12d045.png)

**Comment by xaoxuu** [comment]
全局搜一下「欢迎光临小站」，找到的全删了看看。

**Comment by xaoxuu** [comment]
我试了下没有 `hexo c` 这样的指令：
```
INFO  Validating config
INFO  
=======================================================
  Stellar 1.4.0
  Docs: https://xaoxuu.com/wiki/stellar/
  Repo: https://github.com/xaoxuu/hexo-theme-stellar/
=======================================================
Usage: hexo <command>

Commands:
  clean     Remove generated files and cache.
  config    Get or set configurations.
  deploy    Deploy your website.
  generate  Generate static files.
  help      Get help on a command.
  init      Create a new Hexo folder.
  list      List the information of the site
  migrate   Migrate your site from other system to Hexo.
  new       Create a new post.
  publish   Moves a draft post from _drafts to _posts folder.
  render    Render files with renderer plugins.
  server    Start the server.
  version   Display version information.

Global Options:
  --config  Specify config file instead of using _config.yml
  --cwd     Specify the CWD
  --debug   Display all verbose messages in the terminal
  --draft   Display draft posts
  --safe    Disable all plugins and scripts
  --silent  Hide output on console

For more help, you can use 'hexo help [command]' for the detailed information
or you can check the docs: http://hexo.io/docs/
```

**Comment by hermitlsr** [comment]
我再次使用 `hexo clean && hexo g && hexo c` 结果还是如之前截图情况。但我通过测试发现这个bug的疑似原因，主题对 `widge` 设置的读取采用了站点文件夹的 `_config.stellar.yml`  和主题文件夹的 `_config.yml` 并且优先采用了主题文件夹中的设置。
我更改了主题文件夹的 `_config.yml` 设置为：
```yml
  widgets:
    # default layout in home/wiki/categories/tags/archives pages
    default_layout: [welcome, recent]
    # Recent update
    recent:
      layout: recent
      rss: # /atom.xml # npm i hexo-generator-feed
      limit: 5 # Count of posts
    # TOC (valid only in layout:post/wiki)
    toc:
      layout: toc
      list_number: false
      min_depth: 2
      max_depth: 5
      fallback: recent # Use a backup widget when toc does not exist.
    # welcome
    welcome:
      layout: markdown
      title: 公告
      content:
        - '这是hermitlee的个人学习记录站'
```

保持站点设置为前述的：
```yml
  widgets:
    # default layout in home/wiki/categories/tags/archives pages
    default_layout: [notice, recent]
    # Recent update
    recent:
      layout: recent
      rss: # /atom.xml # npm i hexo-generator-feed
      limit: 5 # Count of posts
    # TOC (valid only in layout:post/wiki)
    toc:
      layout: toc
      list_number: false
      min_depth: 2
      max_depth: 5
      fallback: recent # Use a backup widget when toc does not exist.
    # notice
    notice:
      layout: markdown
      title: 欢迎
      content:
        - '这是hermitlee的个人学习记录站'
```
这两个设置的区别在于 `title` 分别为 欢迎 和 公告
最终效果如下图：
![](https://bu.dusays.com/2021/07/28/f0671b59eedd9.png)

可以看到主题文件夹中的 `welcome` 还是居于最上面，以此推断是优先采取了主题文件夹的设置，再采用站点文件夹时没有覆盖掉
