### ISSUE TITLE
Some problem about swiper plugin

### ISSUE THREAD

**Issue by Avalon1997** [xaoxuu/hexo-theme-stellar#218]
```
{% swiper effect:cards width:max %}
{% image Wafer1.jpeg %}
{% image Wafer2.jpg %}
{% image Wafer3.jpg %}
{% endswiper %}
```

This is my code, but it doesn't work!!!
![image](https://user-images.githubusercontent.com/89969876/207822091-2e332357-60c7-40f4-9771-4b4a3e014e7a.png)

**Comment by xaoxuu** [comment]
请提供链接：

**Comment by Avalon1997** [comment]
The blog under my domain is an old version.
New version can only watch on my local environment.

**Comment by shaoyaoqian** [comment]
be watched

**Comment by parasolwaddledee** [comment]
If you are using the latest v1.18.1 version of stellar, please also try to update the swiper version under _config.stellar.yml:
```yml
  # swiper
  swiper:
    enable: true
    css: https://unpkg.com/swiper@8/swiper-bundle.min.css
    js: https://unpkg.com/swiper@8/swiper-bundle.min.js
```
