### ISSUE TITLE
设置字体无效

### ISSUE THREAD

**Issue by csthenry** [xaoxuu/hexo-theme-stellar#274]
在_config.stellar文件里写了
```
style:
  font-family:
    logo: 'HarmonyOS_Medium'
    body: 'HarmonyOS_Regular'

```
字体也不生效！（已经引入了css如下）

```
# font
inject:
  head:
    - <link rel="preconnect" href="//s1.hdslb.com/" />
    - <link rel="stylesheet" href="//s1.hdslb.com/bfs/static/jinkela/long/font/regular.css" media="all" onload="this.media='all'" />
    - <link rel="stylesheet" href="//s1.hdslb.com/bfs/static/jinkela/long/font/medium.css" media="all" onload="this.media='all'" />

```
