### ISSUE TITLE
代码块显示可能有些问题，或者我配置有问题？可以帮忙看看不

### ISSUE THREAD

**Issue by xq773939719** [xaoxuu/hexo-theme-stellar#296]
_config.yml
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/45348685/2ad4c255-f55f-4b7f-a8d5-1901dff92bd0)

_config.stellar.yml
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/45348685/093d80e9-d250-426e-9182-312894c7d0c3)

写法如下
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/45348685/9d6c7407-d9fb-478e-a883-6eba628c35e7)

现象
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/45348685/8cecabd0-1502-48f3-87f8-33d39fdd08d1)

没有复制按钮了

如果设置line_number：true，

![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/45348685/7b64c896-def0-4a97-b96c-a8520d50fcf2)

会变成这样子。。。

**Comment by xaoxuu** [comment]
你试一下我这个配置：
```yaml
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: '    '
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: '    '
```
