### ISSUE TITLE
Suggest to add ‘Back to the top of the article’

### ISSUE THREAD

**Issue by gyl-coder** [xaoxuu/hexo-theme-stellar#32]

**Comment by xaoxuu** [comment]
```yaml
footer:
  social:
    - title: Back to Top
      icon: '<img src="xxx"/>'
      url: '#start'
```
