### ISSUE TITLE
高亮更多独立页面 指定menu_id参照文档设置，但是在更多页面无指定的活动按钮

### ISSUE THREAD

**Issue by 354770288** [xaoxuu/hexo-theme-stellar#324]
想实现如图所示效果
![image](https://github.com/xaoxuu/hexo-theme-stellar/assets/36475083/56df996e-9c9d-4795-8cbc-7e1a3451fb42)
参考文档
[更多的独立页面](https://xaoxuu.com/wiki/stellar/pages/#%E6%9B%B4%E5%A4%9A%E7%9A%84%E7%8B%AC%E7%AB%8B%E9%A1%B5%E9%9D%A2)
需要高亮在更多内的活动按钮，照搬文档写

```
# blog/source/about/index.md
---
menu_id: more
title: 关于
---
```
```
# blog/source/friends/index.md
---
menu_id: more
title: 友链
---
```
主题配置文件中参照文档写，但是在更多页面无指定的活动按钮

```
# blog/_config.stellar.yml
sidebar:
  menu:
    post: '[btn.blog](/)'
    wiki: '[btn.wiki](/wiki/)'
    more: '[更多](/more/)'
```
### more更多页面是否需要新建
/source/，下需要新建/more/index.md页面吗。如果没该文档 点更多按钮直接跳转404
新建/more/index.md页面后，点更多按钮页面也是空白页面，没有menu_id指定了more的页面活动按钮；
