### ISSUE TITLE
使用ketex公式重复渲染

### ISSUE THREAD

**Issue by how1ewu** [xaoxuu/hexo-theme-stellar#365]
例如在markdown中，公式表示为：
```
$$
E=\frac{a}{m}
$$

$$
精度=1 - 错误率
$$
```
![](https://s2.loli.net/2024/01/21/8IvoADdYnXHM5kj.png)
实际显示为：
![](https://s2.loli.net/2024/01/21/KYhzS5dHnFOLvsy.png)
即在正常渲染外出现了额外公式
![](https://s2.loli.net/2024/01/21/MyE6mcjIYOKU5vz.png)
同时存在了mathml和html
![](https://s2.loli.net/2024/01/21/yk9mUFGQCOLwo1H.png)

**Comment by xaoxuu** [comment]
这里也有这个问题吗：

https://xaoxuu.com/wiki/stellar/third-party/katex.html

**Comment by how1ewu** [comment]
> 这里也有这个问题吗：
> 
> https://xaoxuu.com/wiki/stellar/third-party/katex.html

您的博客没有这个现象

**Comment by how1ewu** [comment]
> 这里也有这个问题吗：
> 
> https://xaoxuu.com/wiki/stellar/third-party/katex.html

我想大致找到问题了，如果在md中没有添加katex: true就会出现两次渲染。请问下这个可以调整为只在config中设置吗，文档改成默认为true，如果渲染有错手动false这样，因为早期文档很多，批量更改文档本身迁移性会降低

**Comment by xaoxuu** [comment]
全局开启是吗？

**Comment by how1ewu** [comment]
> 全局开启是吗？

config里面开启了ketex: true，如果md不开启ketex: true则会出现两个渲染，我这里可以复现，不清楚是因为配置的问题还是某个可能存在的模块？
```yaml
```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "7.0.0"
  },
  "dependencies": {
    "hexo": "^7.0.0",
    "hexo-ai-excerpt": "^1.1.1",
    "hexo-auto-category": "^0.2.2",
    "hexo-baidu-url-submit": "^0.0.6",
    "hexo-deployer-git": "^4.0.0",
    "hexo-filter-mermaid-diagrams": "^1.0.5",
    "hexo-generator-archive": "^2.0.0",
    "hexo-generator-baidu-sitemap": "^0.1.9",
    "hexo-generator-category": "^2.0.0",
    "hexo-generator-index": "^3.0.0",
    "hexo-generator-search": "^2.4.3",
    "hexo-generator-sitemap": "^3.0.1",
    "hexo-generator-tag": "^2.0.0",
    "hexo-migrator-wordpress": "^2.1.2",
    "hexo-neat": "^1.0.9",
    "hexo-related-popular-posts": "^5.0.1",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-markdown-it-plus": "^1.0.6",
    "hexo-renderer-stylus": "^3.0.0",
    "hexo-server": "^3.0.0",
    "hexo-theme-landscape": "^1.0.0",
    "minimatch": "^9.0.3"
  }
}
```{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "7.0.0"
  },
  "dependencies": {
    "[hexo](https://npmjs.com/package/hexo)": "[^7.0.0](https://npmjs.com/package/hexo)",
    "[hexo-ai-excerpt](https://npmjs.com/package/hexo-ai-excerpt)": "[^1.1.1](https://npmjs.com/package/hexo-ai-excerpt)",
    "[hexo-auto-category](https://npmjs.com/package/hexo-auto-category)": "[^0.2.2](https://npmjs.com/package/hexo-auto-category)",
    "[hexo-baidu-url-submit](https://npmjs.com/package/hexo-baidu-url-submit)": "[^0.0.6](https://npmjs.com/package/hexo-baidu-url-submit)",
    "[hexo-deployer-git](https://npmjs.com/package/hexo-deployer-git)": "[^4.0.0](https://npmjs.com/package/hexo-deployer-git)",
    "[hexo-filter-mermaid-diagrams](https://npmjs.com/package/hexo-filter-mermaid-diagrams)": "[^1.0.5](https://npmjs.com/package/hexo-filter-mermaid-diagrams)",
    "[hexo-generator-archive](https://npmjs.com/package/hexo-generator-archive)": "[^2.0.0](https://npmjs.com/package/hexo-generator-archive)",
    "[hexo-generator-baidu-sitemap](https://npmjs.com/package/hexo-generator-baidu-sitemap)": "[^0.1.9](https://npmjs.com/package/hexo-generator-baidu-sitemap)",
    "[hexo-generator-category](https://npmjs.com/package/hexo-generator-category)": "[^2.0.0](https://npmjs.com/package/hexo-generator-category)",
    "[hexo-generator-index](https://npmjs.com/package/hexo-generator-index)": "[^3.0.0](https://npmjs.com/package/hexo-generator-index)",
    "[hexo-generator-search](https://npmjs.com/package/hexo-generator-search)": "[^2.4.3](https://npmjs.com/package/hexo-generator-search)",
    "[hexo-generator-sitemap](https://npmjs.com/package/hexo-generator-sitemap)": "[^3.0.1](https://npmjs.com/package/hexo-generator-sitemap)",
    "[hexo-generator-tag](https://npmjs.com/package/hexo-generator-tag)": "[^2.0.0](https://npmjs.com/package/hexo-generator-tag)",
    "[hexo-migrator-wordpress](https://npmjs.com/package/hexo-migrator-wordpress)": "[^2.1.2](https://npmjs.com/package/hexo-migrator-wordpress)",
    "[hexo-neat](https://npmjs.com/package/hexo-neat)": "[^1.0.9](https://npmjs.com/package/hexo-neat)",
    "[hexo-related-popular-posts](https://npmjs.com/package/hexo-related-popular-posts)": "[^5.0.1](https://npmjs.com/package/hexo-related-popular-posts)",
    "[hexo-renderer-ejs](https://npmjs.com/package/hexo-renderer-ejs)": "[^2.0.0](https://npmjs.com/package/hexo-renderer-ejs)",
    "[hexo-renderer-markdown-it-plus](https://npmjs.com/package/hexo-renderer-markdown-it-plus)": "[^1.0.6](https://npmjs.com/package/hexo-renderer-markdown-it-plus)",
    "[hexo-renderer-stylus](https://npmjs.com/package/hexo-renderer-stylus)": "[^3.0.0](https://npmjs.com/package/hexo-renderer-stylus)",
    "[hexo-server](https://npmjs.com/package/hexo-server)": "[^3.0.0](https://npmjs.com/package/hexo-server)",
    "[hexo-theme-landscape](https://npmjs.com/package/hexo-theme-landscape)": "[^1.0.0](https://npmjs.com/package/hexo-theme-landscape)",
    "[minimatch](https://npmjs.com/package/minimatch)": "[^9.0.3](https://npmjs.com/package/minimatch)"
  }
}
```

**Comment by xaoxuu** [comment]
我看了下大概知道了，原本就是会出现两个标签，katex 的 css 文件里隐藏掉了一个，md 里如果设置 `katex:true` 则会引入这个 css ，所以看起来就不会重复了。

**Comment by xaoxuu** [comment]
我提交了代码，你更新一下看看： f51bf788269e9c5de3cd046b9b7a7f34e367bcf9
在 `_config.stellar.yml` 中增加来全局开启：
```yaml
plugins:
  katex:
    enable: true
```
