### ISSUE TITLE
一站多作者配置 - 作者资料页 显示问题

### ISSUE THREAD

**Issue by ericclose** [xaoxuu/hexo-theme-stellar#367]
一站多作者配置 - 作者资料页显示存在问题，具体如下：

##  预期行为

* 作者资料页，仅显示相应作者的文章。

## 实际行为

* 作者资料页，显示所有作者的文章。

## 所用配置

* `_config.stellar.yml`:

```yaml
  # 作者信息配置
  author: 
    base_dir: author # 只影响自动生成的页面路径
    menu_id: post
    sidebar: recent, timeline
```

* `source/_data/authors.yml`:

```yaml
# 作者 1 （默认）
ko:
  name: 'Kenichi Oshima'
  url: https://user.qzone.qq.com/2569356874
  avatar: /assets/avatar/ko-avatar.jpg
  banner: /assets/banner/ko-banner.jpg
  description:

# 作者 2
eric:
  name: 'Eric Close'
  url: https://ericclose.github.io/
  avatar: https://cdn.jsdelivr.net/gh/ericclose/cdn-assets/img/avatar.jpeg
  banner: https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/001.jpg
  description: 'Never really desperate, only the lost of the soul'
```

* [source](https://github.com/XperiaWiki/xperiawiki.github.io)
* [website](https://xperiawiki.github.io/)

## 截图

![author-issue](https://github.com/xaoxuu/hexo-theme-stellar/assets/34526560/984d0769-fd8a-49d6-ba4f-17068f9ef8c5)
