### ISSUE TITLE
关于图片轮播 swiper 插件已无法正常引用旧版本导致轮播失效

### ISSUE THREAD

**Issue by Tikas** [xaoxuu/hexo-theme-stellar#37]
- [x] 我已经查阅并自行测试新旧版本，直接得出以下结论：

### 问题发生原因：

未对 `swiper` 引用版本具体化，导致直接引用最新 `swiper` 版本造成的非安全事故。

### 事故复盘：

`swiper` 图片轮播是非常棒的功能，由于引用的地址并没有做版本号处理，导致 `unpkg.com` 直接读取到 `swiper` 的最新版本。

到 2021-09-24 写稿时止，`swiper` 引用地址读取到的最新版本为： @7.0.6

已经测试，尝试将 `swiper` 引用地址增加版本号引用为 `@6` 时，`swiper` 轮播功能恢复正常！

6 版本的最高版本为：6.8.4

### 解决事故：

定位到 `themes\stellar` 主题目录内的配置文件： `_config.yml`

在 `JS Plugins` 里修改 `swiper` 的引用地址，增加版本号即可！

```
######## JS Plugins ########
  # swiper
  swiper:
    enable: true
    css: https://unpkg.com/swiper@6.8.4/swiper-bundle.min.css
    js: https://unpkg.com/swiper@6.8.4/swiper-bundle.min.js
```
