### ISSUE TITLE
”探索“页面的相关问题

### ISSUE THREAD

**Issue by Vanadiry** [xaoxuu/hexo-theme-stellar#373]
想做一个类似您网站”探索“的页面，参考[实现「笔记」栏目](https://xaoxuu.com/wiki/stellar/wiki-settings/notes.html)，用Wiki实现了一部分，但还有几个问题想请教一下。

1. 左上角的logo和名字能否显示成自己的名字和头像？
2. 怎样添加别的页面到目录里面？

![s](https://github.com/xaoxuu/hexo-theme-stellar/assets/77710715/99525aed-7fe1-4038-8a81-b091e29ff01d)
![r](https://github.com/xaoxuu/hexo-theme-stellar/assets/77710715/352f2cfa-4139-4799-bc8e-d31d9a79e501)

**Comment by weekdaycare** [comment]
最新版本已经不支持更改该页面的logo
关于别的页面到目录中是基于`_data/wiki/notes.yml`中的toc实现的
```yaml
toc:
    - index.md # 关联到 source/notes/index.md
  '日常问题解决方案':
    - mac # 关联到 source/notes/mac.md
  '移动端开发笔记':
    - ios
    - flutter
```

**Comment by xaoxuu** [comment]
1.26.0 版本开始所有页面都可以修改了
```yaml
logo:
  title:
  subtitle:
  avatar:
```
就更主题配置文件中写法一样，复制到wiki或者页面顶部修改即可。

**Comment by Vanadiry** [comment]
感谢解答！

另外在侧边栏加上不属于本wiki目录下的页面，我用了[linklist](https://xaoxuu.com/wiki/stellar/widgets/#linklist)，然后把它加到sidebar。

最后用`breadcrumb: false`隐藏掉面包屑导航，实现了差不多的“探索”页面。


```markdown
---
sidebar: [test, toc]
breadcrumb: false
logo:
  avatar: '[${config.avatar}](/xxx/)'
  title: '[${config.title}](/)'
  subtitle: 'xxx'
---
```

```yaml
# widgets.yml
test:
  layout: linklist
  title: xxx
  columns: 1
  items:
    - icon: xxx
      title: xxx
      url: /xxx/
```
