### ISSUE TITLE
侧边栏页脚图标未居中对齐

### ISSUE THREAD

**Issue by L33Z22L11** [xaoxuu/hexo-theme-stellar#374]
背景：通过CDN引入`font-awesome`图标，使用`<i>`标签在侧边栏页脚调用图标。

配置文件：`_config.stellar.yml`
```yaml
footer:
  social:
    github:
      icon: '<i class="fa-brands fa-github"></i>'
      url: https://github.com/L33Z22L11

inject:
  head:
    - <link href="https://lib.baomitu.com/font-awesome/6.5.1/css/all.min.css" rel="stylesheet">
```

表现：鼠标悬浮在图标上时，图标位于高亮圆角矩形内部的左侧。

预期：给侧边栏页脚图标的父标签`<div class="social-wrap"></div>`增加`text-align: center;`属性，可以较好地解决问题。
