### ISSUE TITLE
icons.yml 定义的名字没起作用，显示成链接

### ISSUE THREAD

**Issue by ericclose** [xaoxuu/hexo-theme-stellar#376]
icons.yml 定义的名字没起作用，显示成链接。

![bug](https://github.com/xaoxuu/hexo-theme-stellar/assets/34526560/b68f395b-5e70-4438-94e3-7d2cacf497c7)

* `source/_data/icons.yml` :

```yaml
heroicons:document-bold: https://cdn.jsdelivr.net/gh/tailwindlabs/heroicons/src/24/solid/document.svg
heroicons:heart-bold: https://cdn.jsdelivr.net/gh/tailwindlabs/heroicons/src/24/solid/heart.svg
heroicons:information-circle-bold: https://cdn.jsdelivr.net/gh/tailwindlabs/heroicons/src/24/solid/information-circle.svg
heroicons:rss-bold: https://cdn.jsdelivr.net/gh/tailwindlabs/heroicons/src/24/solid/rss.svg
```

* `_config.stellar.yml` : 

```yaml
menubar:
  columns: 4 # 一行多少个
  items: # 可按照自己需求增加，符合以下格式即可
    - id: post
      theme: '#1BCDFC'
      icon: heroicons:document-bold
      title: 博客
      url: /
    - id: social
      theme: '#F44336'
      icon: heroicons:heart-bold
      title: 社交
      url: /friends/
    - id: about
      theme: '#3DC550'
      icon: heroicons:information-circle-bold
      title: 关于
      url: /about/


footer:
    rss:
      icon: heroicons:rss-bold
      url: /rss2.xml
```
