### ISSUE TITLE
升级最新主题后，fancybox 没法使用了，求助

### ISSUE THREAD

**Issue by strongduanmu** [xaoxuu/hexo-theme-stellar#385]
例如这篇文章：https://strongduanmu.com/blog/use-wireshark-to-solve-benchmarksql-exception-with-shardingsphere-proxy.html，升级之前 markdown 图片可以使用 fancybox 放大查看，升级最新的 1.26.8 版本后，fancybox 失效，无法放大查看。

<img width="858" alt="image" src="https://github.com/xaoxuu/hexo-theme-stellar/assets/10829171/08539410-ca59-4079-9d7d-8c1eaa0c6903">

fancybox 配置已打开，另外从 Release Note 中搜到一个 replace_original 参数，设置成 true 也没有用。

```
  image:
    fancybox: true # true, false
    replace_original:  #把 markdown 格式的图片解析成图片标签
      enable: true
```

**Comment by xaoxuu** [comment]
已不支持markdown替换功能了，请使用image标签，更新日志中已有说明。

**Comment by xaoxuu** [comment]
https://github.com/xaoxuu/hexo-theme-stellar/releases/tag/1.22.1

**Comment by strongduanmu** [comment]
> 已不支持markdown替换功能了，请使用image标签，更新日志中已有说明。

好的，谢谢。

**Comment by strongduanmu** [comment]
> 你可以通过 [为您的stellar添加medium-zoom](https://www.whbbit.cn/2024/01/14/%E4%B8%BA%E6%82%A8%E7%9A%84stellar%E6%B7%BB%E5%8A%A0medium-zoom/) 来实现功能，无需替换全站图片标签。

感谢大佬，我试下。

**Comment by strongduanmu** [comment]
> 你可以通过 [为您的stellar添加medium-zoom](https://www.whbbit.cn/2024/01/14/%E4%B8%BA%E6%82%A8%E7%9A%84stellar%E6%B7%BB%E5%8A%A0medium-zoom/) 来实现功能，无需替换全站图片标签。

请问这个 zoom-img.js 放在什么位置，我添加了好像没生效。

**Comment by L33Z22L11** [comment]
请参阅 Hexo 官方文档 [脚本（Scripts）](https://hexo.io/zh-cn/docs/plugins.html#%E8%84%9A%E6%9C%AC%EF%BC%88Scripts%EF%BC%89) 一节的内容。

**Comment by xaoxuu** [comment]
这个思路不错，我试了一下发现其实还是可以直接用的，直接修改这个地方的配置，别的什么都不用改：

```yaml
plugins:
  fancybox:
    selector: .md-text img:not([class]), .md-text .image img # 多个选择器用英文逗号隔开
```

原本是通过正则替换文章源码的，维护成本很高，就去掉了。
