### ISSUE TITLE
默认的导航栏和侧边栏无法关闭

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/hexo-theme-stellar#4]
1.0.0版本的导航栏菜单和侧边栏组件删掉之后仍然显示，这个问题将在1.0.1版本中进行修复，望耐心等待。

在1.0.0版本中，可以暂时通过这种方式隐藏：

隐藏默认的菜单按钮：
```yaml
sidebar:
  menu:
    post: '[btn.blog](/)'
    wiki: ''
```

隐藏welcome：
```yaml
welcome:
  layout: markdown
  title: ''
  content: []
```

效果图：
![image](https://user-images.githubusercontent.com/16400144/111860277-7dd79900-8981-11eb-9e1e-e14464637c96.png)
