### ISSUE TITLE
设置友链不生效

### ISSUE THREAD

**Issue by winsoft666** [xaoxuu/hexo-theme-stellar#439]
### 检查清单

- [X] 已经阅读过 [官方文档](https://xaoxuu.com/wiki/stellar/) 相关内容，并尝试进行搜索。
- [X] 尝试过在本地测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。
- [X] 尝试过在 Codespace 中测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。

### 问题描述

添加了友链页面：
```txt
---
menu_id: post
title: 友链
---

{% friends links %}
```

然后在 source\_data\links.yml 文件中添加友链：
```yml
'links':
  - title: v2ex
    url: https://www.v2ex.com/
    avatar: https://www.v2ex.com/static/img/v2ex@2x.png
```

问题：

友链页面可以显示，页面是空白的，没有任何友链。
