### ISSUE TITLE
主导航栏按钮顺序有误

### ISSUE THREAD

**Issue by Cubik65536** [xaoxuu/hexo-theme-stellar#45]
## 版本：
Stellar 1.5.2
hexo: 5.4.0
hexo-cli: 4.3.0

## 问题描述：
我在我的配置文件 `_config.stellar.yml` 里设置了以下按钮：
``` yml
sidebar:
  menu:
    personal_homepage: '[btn.personal_homepage](https://www.cubik65536.top/)'
    home: '[btn.home](/)'
    post: '[btn.blog](/blog/)'
    wiki: '[btn.wiki](/wiki/)'
    notes: '[btn.notes](/notes/)'
    more: '[btn.more](/more/)'
    friends: '[btn.friends](/friends/)'
```

但是不管我怎么改变配置文件里按钮的顺序，`personal_homepage` 对应的位置一直在第二行第一个而不是我把它放置的位置。请问如何可以让该按钮成为第一行第一个？
