### ISSUE TITLE
建议增加聊天会话标签组件

### ISSUE THREAD

**Issue by xaoxuu** [xaoxuu/hexo-theme-stellar#471]
### 检查清单

- [X] 已经阅读过 [官方文档](https://xaoxuu.com/wiki/stellar/) 相关内容，并尝试进行搜索。
- [ ] 尝试过在本地测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。
- [ ] 尝试过在 Codespace 中测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。

### 问题描述

适用于展示聊天对话，但又无法直接提供截图的场景。

用户信息在 `_data/users.yml` 中配置：
```yaml
user1:
  name:
  avatar: 
  label:
    text: 群主
    textColor: white
    bgColor: #2196f3
user2:
  name:
  avatar: 
```

用法：

```
{% chat style:wechat/qq [title:导航栏标题可选] %}
{% chattip 2024年5月22日 21:43 %}
{% chatcell user:user1 你好 %} // 文字消息，默认靠左布局
{% chatcell user:user2 align:right Are U OK %} // 文字消息，靠右布局（我发送的消息）
{% chatcell user:user3 image:src %} // 图片消息（默认支持fancybox）
{% chatcell user:user3 emoji:xxx %} // 表情包消息（这里用的是emoji组件的资源，标准emoji的话直接输入就行）
{% chatcell user:user1 voice:src %} // 语音消息（可播放）
{% chatcell user:user1 video:src %} // 视频消息（可播放）
{% chatcell user:user1 link:href %} // 链接卡片消息（可点击跳转）
{% chatcell user:user1 file:href %} // 文件消息（可下载）
{% endchat %}
```

> 如果有时间的话，把 `frame` 组件的设备模型图加上，就更像了。
