### ISSUE TITLE
移动端夸克浏览器适配问题

### ISSUE THREAD

**Issue by L33Z22L11** [xaoxuu/hexo-theme-stellar#477]
### 检查清单

- [X] 已经阅读过 [官方文档](https://xaoxuu.com/wiki/stellar/) 相关内容，并尝试进行搜索。
- [X] 尝试过在本地测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。
- [ ] 尝试过在 Codespace 中测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。

### 问题描述

![夸克APP和Edge对比](https://github.com/xaoxuu/hexo-theme-stellar/assets/33976233/edb1454c-46d1-415f-86af-10e21651a026)

经过调试检测，发现是夸克端不支持深色模式。

代码中有大量 `@media (prefers-color-scheme: light)`，希望移除这些媒体查询，或者设置 `@media (prefers-color-scheme: no-preference)` 对应的样式。

另外参见 https://github.com/xaoxuu/hexo-theme-stellar/commit/f36e6b940f6d1898737e41380209113b705f6708 的评论。

**Comment by xaoxuu** [comment]
因为写法不统一造成部分内容用了深色的方案？

**Comment by L33Z22L11** [comment]
是「什么方案都没用」

**Comment by L33Z22L11** [comment]
一部分浏览器根本不认 `prefers-color-scheme` 媒体特性，例如这段代码对于夸克APP根本不生效：

```css
@media (prefers-color-scheme: no-preference) {
  * {
    background: red;
  }
}

@media (prefers-color-scheme: light) {
  * {
    background: green;
  }
}

@media (prefers-color-scheme: dark) {
  * {
    background: blue;
  }
}
```

因此我建议将明亮模式作为不支持媒体特性的默认值，深色模式再单独处理。
