### ISSUE TITLE
Markdown多级列表 二级列表及以下均不显示code背景色

### ISSUE THREAD

**Issue by Amia33** [xaoxuu/hexo-theme-stellar#495]
### 检查清单

- [X] 已经阅读过 [官方文档](https://xaoxuu.com/wiki/stellar/) 相关内容，并尝试进行搜索。
- [X] 尝试过在本地测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。
- [X] 尝试过在 Codespace 中测试运行官方 [demo](https://github.com/xaoxuu/hexo-theme-stellar-examples/) 源码。

### 问题描述

<details>
  <summary>Markdown code</summary>

```markdown
- **`errors`**  {% mark array[object] color:light %}  {% mark Required color:red %}
  - **`code`**  {% mark integer color:light %}  {% mark Required color:red %}  
  `>= 1000`  > This line <
  - **`message`**  {% mark string color:light %}  {% mark Required color:red %}
- **`messages`**  {% mark array[string] color:light %}  {% mark Required color:red %}
- **`result`**  {% mark object or null color:light %}  {% mark Required color:red %}  
Allowed values: `null`
- **`success`**  {% mark boolean color:light %}  {% mark Required color:red %}  
Whether the API call was successful  
Allowed value: `false`  
Example: `false`
```

</details>
<details>
  <summary>/config.yml</summary>

```yaml
highlight:
  auto_detect: false
  exclude_languages:
    - 'plaintext'
  hljs: false
  line_number: true  ## Note: tried issue#296 but not working either
  line_threshold: 0
  tab_replace: ''
  wrap: true
syntax_highlighter: 'highlight.js'
```

</details>
Expected (VScode Preview):

![vscode](https://github.com/xaoxuu/hexo-theme-stellar/assets/137411471/ab0f6e6b-d7a3-4f03-a78b-dce0c32727d4)
Running theme v1.29.0:

![theme](https://github.com/xaoxuu/hexo-theme-stellar/assets/137411471/c15b5ed3-6867-4613-b336-c181482cbee5)
