### ISSUE TITLE
toc中当前所在标题没有颜色

### ISSUE THREAD

**Issue by sevichee** [xaoxuu/hexo-theme-stellar#60]
- **问题**：我的toc没有像下面这样，滚到相应的标题会变颜色

![image](https://user-images.githubusercontent.com/91365763/151660004-faa5aa36-4c2a-4ec5-8c92-4ca88e9dd063.png)

- **示例网址**：https://www.seviche.top/blog/ux4/

- **浏览器**：Chrome

- **报错**： 报错里面有jquery的网址很奇怪，不知道是哪里设置出了错 （我没有改过`_config.stellar.yml`里jquery的路径

![image](https://user-images.githubusercontent.com/91365763/151660097-5fb9bb28-648d-403d-8e44-0e4374cc6680.png)

---

我的`_config.stellar.yml`设置：
```yml
######## Stellar info ########
stellar:
  version: '1.6.1'
  homepage: 'https://xaoxuu.com/wiki/stellar/'
  repo: 'https://github.com/xaoxuu/hexo-theme-stellar'


######## head tags ########
open_graph:
  enable: true
  twitter_id: # for open_graph meta


######## Sidebar ########
sidebar:
  logo:
   # avatar: '[https://raw.githubusercontent.com/sevichee/obsidian-image/main/img202201280038578.png](/about/)' # you can set avatar link in _config.yml or '[https://xxx.png](/about/)'
    title: '[config.title](/)' # you can set html tag like: '[<img no-lazy height="32px" src="xxx"/>](/)'
  menu:
     post: '[btn.blog](/)'
     wiki: '[系列](/wiki/)'
     notes: '[便笺](/links/)'
     more: '[关于](/about/)'
  # Sidebar widgets
  widget_layout:
    index: [welcome, recent] # for home/wiki/categories/tags/archives/404 pages
    page: [welcome, toc] # for pages using 'layout:page'
    post: [toc, repo_info] # for pages using 'layout:post'
    wiki: [toc, repo_info, wiki_more] # for pages using 'layout:wiki'
  widgets:
    # Recent update
    recent:
      layout: recent
      rss: /atom.xml # npm i hexo-generator-feed
      limit: 5 # Count of posts
    # TOC (valid only in layout:post/wiki)
    toc:
      layout: toc
      list_number: false
      min_depth: 2
      max_depth: 5
      fallback: recent # Use a backup widget when toc does not exist.
    # welcome
    welcome:
      layout: markdown
      title: 欢迎 :D
      content: | # support markdown
        书签：[About Coding](https://airtable.com/shrpftxf6JgRomP2X/tblEvtThXHNBMQ8lW/viwSXGTALloahC10H)
        站内： [友链](/friends) ｜ [留言](/board)
   


######## Main ########
breadcrumb:
  home: home # config.title / config.author / home or custom content

######## Article ########
article:
  # 如果没有指定封面，是否根据 tags 作为关键词搜索封面？
  auto_cover: false # search from https://source.unsplash.com/
  # 如果没有指定 excerpt 和 description，将自动取多长的内容作为文章摘要？
  auto_excerpt: 200
  # 分类颜色
  category_color:
    '新闻稿': '#DA0F47'

  # 文章许可协议
  license: '本文采用 [署名-非商业性使用-相同方式共享 4.0 国际](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。'
  # 分享
  share:  [wechat, weibo, email, link]
  # 相关文章，需要安装插件 (for layout: post)
  # npm i hexo-related-popular-posts
  related_posts:
    enable: false
    max_count: 5
    auto_cover: false # 如果没有封面就根据 tags 作为关键词搜索封面，开了此项将不会自动从文章中提取首张图片作为封面了。



######## Comments ########
comments:
  service:  beaudar #, utterances, valine, twikoo
  beaudar:
    repo: sevichee/beaudar
    issue-term: pathname
    issue-number:
    theme: preferred-color-scheme
    label:
    input-position: top # top/bottom 评论框位置
    comment-order: desc # desc 排序
    keep-theme: # true/false
    loading: false
    branch: main

######## Footer ########
footer:
  license: '[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)'

######## Tag Plugins ########
tag_plugins:
  # {% note text %}
  note:
    default_color: '' # light, dark, red, orange, yellow, green, cyan, blue, purple
  # {% checkbox %}
  checkbox:
    interactive: false # enable interactive for user
  # {% quot %}
  quot:
    default: # 可以自行配置多种图标方案
      prefix: https://s2.loli.net/2022/01/04/vsTB5pGrIHfPxSj.png
      suffix: https://s2.loli.net/2022/01/04/NORdtjlAhifZSns.png
    hashtag:
      prefix: https://s2.loli.net/2022/01/04/UvHcsa73jQPnobq.png
  # {% emoji %}
  emoji:
    default: https://cdn.jsdelivr.net/gh/volantis-x/cdn-emoji/qq/%s.gif
    twemoji: https://cdn.jsdelivr.net/gh/twitter/twemoji/assets/svg/%s.svg
    qq: https://cdn.jsdelivr.net/gh/volantis-x/cdn-emoji/qq/%s.gif
    aru: https://cdn.jsdelivr.net/gh/volantis-x/cdn-emoji/aru-l/%s.gif
    tieba: https://cdn.jsdelivr.net/gh/volantis-x/cdn-emoji/tieba/%s.png
  # {% image %}
  image:
    fancybox:  true #, false


######## JS Plugins ########
plugins:
  scrollreveal:
    enable: false
    js: https://cdn.jsdelivr.net/npm/scrollreveal@4.0.9/dist/scrollreveal.min.js
    distance: 8px
    duration: 500 # ms
    interval: 100 # ms
    scale: 1 # 0.1~1

  # https://fancyapps.com/docs/ui/fancybox/
  # available for {% image xxx %}
  fancybox:
    enable: true
    js: https://cdn.jsdelivr.net/npm/@fancyapps/ui@4.0/dist/fancybox.umd.js
    css: https://cdn.jsdelivr.net/npm/@fancyapps/ui@4.0/dist/fancybox.css
    # 可以处理评论区的图片（不支持 iframe 类评论系统）例如：
    # 使用valine评论可以写: .vcontent img:not(.vemoji)
    # 使用twikoo评论可以写: .tk-content img:not([class*="emo"])
    selector: .swiper-slide img # 多个选择器用英文逗号隔开

  # swiper
  swiper:
    enable: true
    css: https://unpkg.com/swiper@6/swiper-bundle.min.css
    js: https://unpkg.com/swiper@6/swiper-bundle.min.js

style:
  darkmode: auto # auto / always / false
  theme:
    light: '#f8f9fa'
    dark: '#313438'
  animated_avatar:
    animate: auto # auto, always
    background: https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.2/avatar/round/rainbow64@3x.webp
  codeblock:
    scrollbar: 4px

default:
  avatar: https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.1/avatar/round/3442075.svg
  link: https://raw.githubusercontent.com/sevichee/obsidian-image/main/img202201272235750.svg
  cover: https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.1/cover/76b86c0226ffd.svg
  image: https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.1/image/2659360.svg

```

我的`_config.yml`设置：
```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Seviche
subtitle: 酸橘汁腌鱼|在学JavaScript
description: 前端/设计/读书
keywords:
avatar:  https://cdn.jsdelivr.net/gh/sevichee/obsidian-image@2.0/favicon/android-chrome-512x512.png
author: Seviche
language: [zh-CN, en, zh-CN, zh-TW]
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://seviche.top
root: /
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks


# Directory
source_dir: source
public_dir: public
# tag_dir: tags
# archive_dir: archives
# category_dir: categories
tag_dir: blog/tags
archive_dir: blog/archives
category_dir: blog/categories
wiki_dir: wiki
i18n_dir: :lang
skip_render:
  - assets/*


# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 1
render_drafts: false
post_asset_folder: false
# marked:
#   prependRoot: true
#   postAsset: true
relative_link: true
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: '    '
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: '  '
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: ll
time_format: HH:mm:ss
updated_option: 'date'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 0
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: stellar

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

inject:
  head:
    - <link rel="preconnect" href="https://fonts.googleapis.com">
    - <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    - <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,400&display=swap" rel="stylesheet">
    - <link rel="apple-touch-icon" sizes="180x180" href="https://cdn.jsdelivr.net/gh/sevichee/obsidian-image@2.0/favicon/apple-touch-icon.png">
    - <link rel="icon" type="image/png" sizes="32x32" href="https://cdn.jsdelivr.net/gh/sevichee/obsidian-image@2.0/favicon/favicon-32x32.png">
    - <link rel="icon" type="image/png" sizes="16x16" href="https://cdn.jsdelivr.net/gh/sevichee/obsidian-image@2.0/favicon/favicon-16x16.png">
    - <link rel="manifest" href="https://cdn.jsdelivr.net/gh/sevichee/obsidian-image@2.0/favicon/site.webmanifest">
    - <link rel="shortcut icon" href="https://cdn.jsdelivr.net/gh/sevichee/obsidian-image@2.0/favicon/favicon.ico">
    - <meta name="theme-color" content="#f8f9fa">
########################### Plugins ###########################
# npm i hexo-generator-feed
feed:
  type: atom
  path: atom.xml
  limit: false
  content: true
  # icon: https://cdn.jsdelivr.net/gh/cdn-x/xaoxuu/avatar/rect-256@2x.png
  autodiscovery: true

# npm i hexo-related-popular-posts

# npm i hexo-neat
neat_enable: false

# npm i hexo-all-minifier
all_minifier: true

# npm i hexo-autonofollow
nofollow:
  enable: true
  exclude:
    - seviche.top

# https://github.com/ludoviclefevre/hexo-generator-seo-friendly-sitemap
sitemap:
  path: sitemap.xml
  tag: false
  category: false
  page_priority: 0.4
  post_priority: 0.6
```
