### ISSUE TITLE
希望能加入对数学公式的支持

### ISSUE THREAD

**Issue by Heyya-x** [xaoxuu/hexo-theme-stellar#67]
Stellar是一个简洁而高级的主题，期待作者能完善对数学公式的支持，个人认为在学术笔记博客中还是数学公式频繁出现的。

十分感谢！

**Comment by xaoxuu** [comment]
求个PR

**Comment by zhenxiang-shawn** [comment]
同求加入对LaTeX的支持

**Comment by hermitlsr** [comment]
这是我的做法使用 katex，效果还是很不错的，不过这个不好提PR

参考 https://www.micdz.cn/article/katex-on-volantis/

1.首先更换公式编译插件：
```
npm uninstall hexo-renderer-marked --save
npm install hexo-renderer-markdown-it-plus --save
```
2.在站点根文件中 _config.yml 设置：
```
# npm i hexo-renderer-markdown-it-plus
markdown_it_plus:
    highlight: true
    html: true
    xhtmlOut: true
    breaks: true
    langPrefix:
    linkify: true
    typographer:
    quotes: “”‘’
    plugins:
        - plugin:
            name: markdown-it-mark
            enable: false
```
3.根据进阶设定中的外部文件注入，在 _config.yml 中添加如下：
```
inject:
  head:
    - <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css" integrity="sha384-AfEj0r4/OFrOo5t7NnNe46zW/tFgW6x/bCJG8FqQCEo3+Aro6EYUG4+cU+KJWu/X" crossorigin="anonymous">
    - <script defer src="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.js" integrity="sha384-g7c+Jr9ZivxKLnZTDUhnkOnsh30B4H0rpLUpJ4jAIKs4fnJI+sEnkvrMWph2EDg4" crossorigin="anonymous"></script>
    - <script defer src="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/contrib/auto-render.min.js" integrity="sha384-mll67QQFJfxn0IYznZYonOWZ644AWYC+Pt2cHqMaRhXVrursRwvLnLaebdGIlYNa" crossorigin="anonymous" onload="renderMathInElement(document.body);"></script>

  script:
```
