### ISSUE TITLE
功能改进建议：根据主题明暗改变侧边栏中的 social icon

### ISSUE THREAD

**Issue by Cubik65536** [xaoxuu/hexo-theme-stellar#69]
希望可以通过将配置文件改成例如下面这样实现在明暗效果不一样的时候使用不同的 icon。因为目前如果使用同一个 icon，在白色模式下可能会看不见为暗黑模式设置的白色图标，而反之亦然。

``` yml
footer:
  social:
    light:
      - icon: '<img src="https://cdn.jsdelivr.net/gh/Rush/Font-Awesome-SVG-PNG@master/black/svg/github.svg"/>'
        url: https://github.com/
    dark:
      - icon: '<img src="https://cdn.jsdelivr.net/gh/Rush/Font-Awesome-SVG-PNG@master/white/svg/github.svg"/>'
        url: https://github.com/
```
